workflows:
  android-workflow:
    name: ToTV+ Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      flutter: stable
      java: 17
      
    scripts:
      - name: Get Flutter packages
        script: flutter packages pub get
        
      - name: Build APK
        script: flutter build apk --release --split-per-abi
        
    artifacts:
      - build/**/outputs/**/*.apk
      
    publishing:
      email:
        recipients:
          - user@example.com
