workflows:
  android-workflow:
    name: ToTV+ Android Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      groups:
        - google_play # إذا كنت تريد الربط لاحقاً
    scripts:
      - name: Set up local.properties
        script: | 
          echo "flutter.sdk=$FLUTTER_ROOT" > android/local.properties
      
      - name: Fix Dependencies and Version Conflict
        script: | 
          # هذا السطر يحل مشكلة intl التي واجهتنا
          flutter pub add intl:^0.20.2
          flutter pub get

      - name: Clean Project
        script: | 
          flutter clean
          flutter pub get

      - name: Build APK (Release)
        script: | 
          # بناء نسخة APK وتجاهل أخطاء iOS تماماً
          flutter build apk --release --no-tree-shake-icons

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
    
    publishing:
      email:
        recipients:
          - YOUR_EMAIL@gmail.com # ضع إيميلك هنا ليصلك الرابط
