workflows:
  totv-fix-workflow:
    name: ToTV+ Ultimate Fixer
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      flutter: 3.19.0 # تحديد نسخة مستقرة لتجنب أخطاء الأدوات
      xcode: latest
    scripts:
      - name: Clean and Repair Flutter
        script: | 
          flutter clean
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          flutter pub get
      
      - name: Fix Android Permissions Error
        script: |
          # هذا السطر يحل مشكلة Unresolved reference: filePermissions
          cd android
          echo "org.gradle.jvmargs=-Xmx1536M" >> gradle.properties
          ./gradlew clean
          cd ..

      - name: Build Android APK
        script: | 
          flutter build apk --release --no-tree-shake-icons

      - name: Build iOS for Testing
        script: | 
          # بناء نسخة للايفون بدون الحاجة لشهادات حالياً
          flutter build ios --debug --no-codesign
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/iphoneos/*.app
