workflows:
  totv-build-fix:
    name: TOTV+ Final Success Build
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: 3.24.0 # هذا السطر هو مفتاح الحل
      java: 17
    scripts:
      - name: Reset Flutter and Gradle
        script: | 
          flutter clean
          flutter pub get
          cd android
          # إجبار Gradle على تجاهل أي إعدادات تالفة في الأدوات
          echo "android.suppressUnsupportedCompileSdk=34" >> local.properties
          chmod +x gradlew
          cd ..
      - name: Build Android Release APK
        script: | 
          # السر: بناء النسخة النهائية (Release) يتجاهل أخطاء الـ Debug في فلاتر
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
