workflows:
  totv-plus-workflow:
    name: ToTV+ Multi-Platform Fixer
    max_build_duration: 30
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest # ضروري لبناء ملفات الأيفون
      cocoapods: default
    scripts:
      - name: Auto-Create iOS Files
        script: | 
          # هذا الأمر يعيد بناء مجلد ios إذا كان ناقصاً أو به أخطاء
          flutter create . --platforms=ios,android
          
      - name: Force Fix Dependencies (intl & others)
        script: | 
          # حل مشكلة تعارض الإصدارات إجبارياً
          flutter pub add intl:^0.20.2
          flutter pub get

      - name: iOS Dependency Manager (Pods)
        script: | 
          # تهيئة ملفات الأيفون الداخلية
          cd ios
          pod install
          cd ..

      - name: Build Android APK
        script: | 
          flutter build apk --release --no-tree-shake-icons

      - name: Build iOS (No-Sign)
        script: | 
          # بناء نسخة iOS تجريبية للتأكد من سلامة الكود
          flutter build ios --debug --no-codesign

    artifacts:
      - build/app/outputs/flutter-apk/*.apk
      - build/ios/iphoneos/*.app
    
    publishing:
      email:
        recipients:
          - haedirasso@gmail.com # ضع إيميلك هنا ليصلك رابط التحميل
